name: Build .dat files

on:
  push:
    branches:
      - master
    paths:
      - "geoip_config.json"
  repository_dispatch:
    types: [trigger-dat-build]
  workflow_dispatch:
    inputs:
      message:
        description: 'Release message'
        required: true
        type: string

permissions:
  contents: write

env:
  LISTS_REPO: "https://raw.githubusercontent.com/itdoginfo/allow-domains/refs/heads/main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout config
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            geoip_config.json
          sparse-checkout-cone-mode: false
          path: publish

      - name: Checkout lists
        uses: actions/checkout@v6
        with:
          repository: itdoginfo/allow-domains
          sparse-checkout: |
            Russia/inside-raw.lst
            Russia/outside-raw.lst
            Ukraine/inside-raw.lst
            Categories
            Services
            Subnets
          sparse-checkout-cone-mode: false
          path: lists

      - name: Checkout geosite builder
        uses: actions/checkout@v6
        with:
          repository: v2fly/domain-list-community
          sparse-checkout: |
            main.go
            go.mod
            go.sum
            internal
          sparse-checkout-cone-mode: false
          path: geosite

      - name: Checkout geoip builder
        uses: actions/checkout@v6
        with:
          repository: v2fly/geoip
          path: geoip

      - name: Setup Go for geosite builder
        uses: actions/setup-go@v6
        with:
          go-version-file: geosite/go.mod
          cache-dependency-path: geosite/go.sum

      - name: Prepare domains lists
        run: |
          mkdir -p geosite/input && cd geosite/input
          mkdir {allow-domains,allow-categories,allow-countries,allow-services}
          declare -A countries=(
            ["russia-inside"]="Russia/inside-raw"
            ["russia-outside"]="Russia/outside-raw"
            ["ukraine-inside"]="Ukraine/inside-raw"
          )
          for country in "${!countries[@]}"; do
            name="${country//_/-}"
            mkdir "$name"
            dest="$name/list"
            ln "/lists/${country}.lst" "$dest"
            ln "$dest" "allow-countries/$name"
            ln "$dest" "allow-domains/$name"
          done
          declare -a categories=(
            "anime"
            "block"
            "geoblock"
            "hodca"
            "news"
            "porn"
          )
          for category in "${categories[@]}"; do
            name="${category//_/-}"
            mkdir "$name"
            dest="${name}-domains/list"
            ln "/lists/Categories/${category}.lst" "$dest"
            ln "$dest" "allow-categories/$name"
            ln "$dest" "allow-domains/$name"
          done
          declare -a services=(
            "cloudflare"
            "cloudfront"
            "digitalocean"
            "discord"
            "google_ai"
            "google_meet"
            "google_play"
            "hdrezka"
            "hetzner"
            "meta"
            "ovh"
            "roblox"
            "telegram"
            "tiktok"
            "twitter"
            "youtube"
          )
          for service in "${services[@]}"; do
            name="${service//_/-}"
            mkdir "$name"
            dest="${name}-domains/list"
            ln "/lists/Services/${service}.lst" "$dest"
            ln "$dest" "allow-services/$name"
            ln "$dest" "allow-domains/$name"
          done

      - name: Build domains .dat files
        run: |
          cd geosite
          for category in ./input/*/; do
            go run ./ --datapath="${category}" --outputname="$(basename $category).dat" --outputdir="../publish/"
          done

      - name: Setup Go for geoip
        uses: actions/setup-go@v6
        with:
          go-version-file: geoip/go.mod
          cache-dependency-path: geoip/go.sum

      - name: Download subnets
        run: |
          mkdir -p geoip/input && cd geoip/input
          declare -a subnets=(
            "cloudflare"
            "cloudfront"
            "digitalocean"
            "discord"
            "google_meet"
            "hetzner"
            "meta"
            "ovh"
            "telegram"
            "twitter"
          )
          for subnet in "${subnets[@]}"; do
            dest="${subnet//_/-}"
            ln "/lists/Subnets/IPv4/${subnet}.lst" "$dest"
            cat "/lists/Subnets/IPv6/${subnet}.lst" >> "$dest"
          done
          ln "/lists/Subnets/IPv4/roblox.lst" "roblox"

      - name: Build subnets .dat files
        run: |
          cd geoip
          mkdir -p output
          go run ./ -c ../publish/geoip_config.json
          for filename in ./output/*.dat; do
            mv "${filename}" "../publish/$(basename $filename .dat)-subnets.dat"
          done

      - name: Release and upload assets
        id: release
        run: |
          cd publish
          RELEASE_NAME="$(date +'%Y-%m-%d_%H-%M-%S')"
          gh release create "$RELEASE_NAME" -t "$RELEASE_NAME" -n "${{ env.RELEASE_MSG }}" ./*.dat
          echo "version=$RELEASE_NAME" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ github.token }}
          RELEASE_MSG: "${{
            inputs.message ||
            github.event.head_commit.message ||
            format('new lists release: {0}', github.event.client_payload.version) }}"
          
      - name: Trigger Happ routing rebuild
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.HAPP_ROUTING_TOKEN }}
          repository: KazZzeL/allow-domains-happ-routing
          event-type: trigger-routing-build
          client-payload: '{"version": "${{ steps.release.outputs.version }}"}'
          