name: Update latest release version

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-version:
    runs-on: ubuntu-slim

    steps:
      - name: Checkout current release version
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          sparse-checkout: |
            latest_version.txt
          sparse-checkout-cone-mode: false
          persist-credentials: true

      - name: Fetch latest release version
        run: |
          latest_version=$(curl -fsSL "https://api.github.com/repos/itdoginfo/allow-domains/releases/latest" | jq -r ".tag_name")
          if [[ -n $latest_version && $latest_version != "null" ]]; then
            echo "$latest_version" > latest_version.txt
          fi

      - name: Check for changed release version
        id: diff
        run: |
          if [[ -z "$(git status --porcelain)" ]]; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo -e "changed=true\nversion=$(head -n 1 latest_version.txt)" >> $GITHUB_OUTPUT
          fi

      - name: Commit changed release version
        if: steps.diff.outputs.changed == 'true'
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
        with:
          commit_message: "chore: new lists release (${{ steps.diff.outputs.version }})"
          file_pattern: "latest_version.txt"
          skip_push: false

      - name: Trigger .dat files build
        if: steps.diff.outputs.changed == 'true'
        uses: peter-evans/repository-dispatch@28959ce8df70de7be546dd1250a005dd32156697 # v4.0.1
        with:
          event-type: trigger-dat-build
          client-payload: '{"version": "${{ steps.diff.outputs.version }}"}'
